name: My workflow

on: 
  pull_request:
     branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      run: |
        # Extract the branch name from the GITHUB_REF variable
        branch_name1=$(echo $GITHUB_REF | cut -d '/' -f 1)
        branch_name2=$(echo $GITHUB_REF | cut -d '/' -f 2)
        branch_name3=$(echo $GITHUB_REF | cut -d '/' -f 3)
        branch_name4=$(echo $GITHUB_REF | cut -d '/' -f 4)
        branch_name5=$(echo $GITHUB_REF | cut -d '/' -f 5)
        echo "Branch name: $branch_name1"
        echo "Branch name: $branch_name2"
        echo "Branch name: $branch_name3"
        echo "Branch name: $branch_name4"
        echo "Branch name: $branch_name5"
