name: learn-github-actions
on:
  push:
    branches: [ main ]
jobs:
  testing-shell:
    runs-on: ubuntu-20.04
    steps:
    - run: sudo apt-get update
    - name: run shell script
      run: sh .github/workflows/scripts/kind.sh
