name: learn-github-actions
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
#      inputs:
#         name:
#           required: true
#           default: nishant

env:
   fname: ${{ github.event.inputs.name }}
        
jobs:
  testing-shell:
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v3
    
    - name: run shell script
      id: files
      run: |
        ls -ltr
        
    - name: Save step logs to file
      run: |
         echo "${{ github.run_id }}" > logs.txt
     
    - name: Download artifacts
      uses: actions/upload-artifact@v3
      with:
        #run_id: ${{ github.run_id }}
        name: artifacts
        path: logs.txt

    - name: Save step logs to file
      run: |
         echo "${{ github.run_id }}" > logs.txt
         
    - name: Print log
      run: |
        echo "This is a log message"
        echo "::set-output name=logs::This is a log message"
      id: print_log
    
    - name: Print the logs
      run: echo "Logs is ${{ steps.print_log.outputs.logs }}"
        
    - name: run shell script
      id: files1
      run: |
        cat logs.txt
