name: learn-github-actions
on:
  push:
    branches: [ main ]
jobs:
  testing-shell:
    runs-on: ubuntu-20.04
    steps: 
    - name: run shell script
      run: sudo sh .github/workflows/scripts/kind.sh
