name: learn-github-actions
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
#      inputs:
#         name:
#           required: true
#           default: nishant

env:
   fname: ${{ github.event.inputs.name }}
        
jobs:
  testing-shell:
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v3
    
    - name: run shell script
      id: files
      run: |
        ls -ltr
        
    - name: Save step logs to file
      run: |
         "${{ steps.files.outputs.logs }}" > logs.txt
        
    - name: run shell script
      id: files1
      run: |
        cat logs.txt
