name: learn-github-actions
on:
  push:
    branches: [ main ]
jobs:
  testing-shell:
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v2
    - name: run shell script
      run: |
        sh .github/workflows/scripts/kind.sh
      env:
       ID: "${{ secrets.TOKEN }}"
       USER: "${{ secrets.NISH }}"
